"""Transcript core: envelope classification, turn extraction, incremental slicing."""

from __future__ import annotations

from wikiforge.ops.transcript import (
    Turn,
    is_human_request,
    iter_turns,
    last_entry_uuid,
    strip_envelopes,
    turns_since,
)

# The five polluting shapes measured across 60 real transcripts on 2026-07-20.
_SKILL = (
    "Base directory for this skill: "
    "/Users/x/.claude/plugins/cache/superpowers/skills/brainstorming"
)
_CMD = (
    "<command-message>superpowers:using-superpowers</command-message>\n"
    "<command-name>/superpowers:using-superpowers</command-name>"
)
_CAVEAT = (
    "<local-command-caveat>Caveat: The messages below were generated by the "
    "user while running local commands.</local-command-caveat>"
)
_STDOUT = "<local-command-stdout>Set model to claude-opus-4-8</local-command-stdout>"
_REMINDER = "<system-reminder>Remember to be helpful.</system-reminder>"

# The realistic skill-invocation shape, measured on 120 real transcripts on 2026-07-20:
# command-message + command-name + skill preamble + skill body, with the user's actual
# request appearing ONLY in a trailing `ARGUMENTS:` line for 28 of 46 such messages.
_SKILL_BODY = (
    "# Brainstorming Ideas Into Designs\n"
    "Ask clarifying questions before writing any implementation code.\n"
    "Then produce a short design doc summarizing the chosen approach.\n"
)
_UKRAINIAN_REQUEST = "що можна покращити в wikiforge? для кращої memory для оптимізації."


def _skill_message(arguments: str | None) -> str:
    """Build a realistic slash-command-with-skill user message.

    ``arguments`` is the trailing ``ARGUMENTS:`` line's content, or ``None`` to
    build the pure-preamble shape (no user words anywhere).
    """
    text = (
        "<command-message>superpowers:brainstorming</command-message>\n"
        "<command-name>/superpowers:brainstorming</command-name>\n"
        "Base directory for this skill: "
        "/Users/x/.claude/plugins/cache/superpowers/skills/brainstorming\n\n"
        f"{_SKILL_BODY}"
    )
    if arguments is not None:
        text += f"\nARGUMENTS: {arguments}"
    return text


def _user(text: str, uuid: str = "u1") -> dict:
    return {"uuid": uuid, "message": {"role": "user", "content": [{"type": "text", "text": text}]}}


def _assistant_edit(path: str, uuid: str = "a1") -> dict:
    return {
        "uuid": uuid,
        "message": {
            "role": "assistant",
            "content": [
                {"type": "text", "text": "editing now"},
                {"type": "tool_use", "name": "Edit", "input": {"file_path": path}},
            ],
        },
    }


def test_strip_envelopes_removes_every_measured_shape() -> None:
    for envelope in (_SKILL, _CMD, _CAVEAT, _STDOUT, _REMINDER):
        assert strip_envelopes(envelope).strip() == ""
    # Real words survive alongside an envelope.
    assert "fix the deadlock" in strip_envelopes(f"{_CMD}\nfix the deadlock")


def test_command_args_are_the_request() -> None:
    """A slash command's arguments ARE the user's instruction — the most valuable line."""
    text = (
        "<command-message>wikiforge:query</command-message>\n"
        "<command-name>/wikiforge:query</command-name>\n"
        "<command-args>why did we pick WAL mode?</command-args>"
    )
    assert strip_envelopes(text).strip() == "why did we pick WAL mode?"


def test_skill_preamble_arguments_tail_is_the_request() -> None:
    """61% of measured skill-invocation messages carry the request ONLY here."""
    text = _skill_message(_UKRAINIAN_REQUEST)
    result = strip_envelopes(text)
    assert result.strip() == _UKRAINIAN_REQUEST
    for word in ("Brainstorming", "clarifying", "design doc", "implementation"):
        assert word not in result


def test_pure_skill_preamble_still_yields_nothing() -> None:
    """The 17 pure-preamble cases (no ARGUMENTS tail) must keep being dropped."""
    text = _skill_message(None)
    assert strip_envelopes(text).strip() == ""


def test_iter_turns_recovers_the_request_from_a_skill_message() -> None:
    """The fix must reach real turn extraction, not just the strip_envelopes helper."""
    entries = [_user(_skill_message(_UKRAINIAN_REQUEST), uuid="u1")]
    turns = iter_turns(entries)
    assert len(turns) == 1
    assert turns[0].request == _UKRAINIAN_REQUEST
    assert "Brainstorming" not in turns[0].request


def test_is_human_request_rejects_envelope_only_messages() -> None:
    assert is_human_request([{"type": "text", "text": "please fix the retry logic"}]) is True
    assert is_human_request([{"type": "text", "text": _SKILL}]) is False
    assert is_human_request([{"type": "tool_result", "content": "ok"}]) is False
    assert is_human_request([{"type": "text", "text": "   "}]) is False


def test_envelope_only_message_does_not_overwrite_the_real_request() -> None:
    entries = [
        _user("add retry logic to the bridge", uuid="u1"),
        _assistant_edit("/r/bridge.py", uuid="a1"),
        _user(_SKILL, uuid="u2"),          # skill preamble must NOT become the request
    ]
    turns = iter_turns(entries)
    assert len(turns) == 1
    assert turns[0].request == "add retry logic to the bridge"
    assert turns[0].files == ["/r/bridge.py"]


def test_iter_turns_splits_on_real_human_turns_and_keeps_assistant_prose() -> None:
    entries = [
        _user("first request", uuid="u1"),
        _assistant_edit("/r/a.py", uuid="a1"),
        _user("second request", uuid="u2"),
        _assistant_edit("/r/b.py", uuid="a2"),
    ]
    turns = iter_turns(entries)
    assert [t.request for t in turns] == ["first request", "second request"]
    assert [t.files for t in turns] == [["/r/a.py"], ["/r/b.py"]]
    assert "editing now" in turns[0].assistant_text
    assert turns[1].uuid == "u2"


def test_turns_since_returns_only_newer_turns() -> None:
    entries = [
        _user("old request", uuid="u1"),
        _assistant_edit("/r/a.py", uuid="a1"),
        _user("new request", uuid="u2"),
        _assistant_edit("/r/b.py", uuid="a2"),
    ]
    assert [t.request for t in turns_since(entries, "u1")] == ["new request"]
    assert [t.request for t in turns_since(entries, None)] == ["old request", "new request"]
    # An unknown watermark must not silently drop everything.
    assert len(turns_since(entries, "does-not-exist")) == 2


def test_last_entry_uuid() -> None:
    assert last_entry_uuid([_user("x", uuid="u1"), _assistant_edit("/r/a.py", uuid="a9")]) == "a9"
    assert last_entry_uuid([]) is None


def test_turn_backwards_compatible_construction() -> None:
    """capture.py and existing tests build Turn with two positional-style kwargs."""
    t = Turn(request="r", files=["/f.py"])
    assert t.assistant_text == "" and t.uuid is None and t.ts is None
